web_server/lib/web_server_web/router.ex
defmodule WebServerWeb.Router do
  use WebServerWeb, :router

  pipeline :browser do
    plug :accepts, ["html"]
    plug :fetch_session
    plug :fetch_flash
    plug :protect_from_forgery
    plug :put_secure_browser_headers
  end

  pipeline :guardian do
    plug WebServerWeb.Authentication.Pipeline
  end

  pipeline :browser_auth do
    plug Guardian.Plug.EnsureAuthenticated
  end

  pipeline :api do
    plug :accepts, ["json"]
  end

  scope "/", WebServerWeb do
    pipe_through :browser

    get "/", PageController, :index
  end

  scope "/", WebServerWeb do
    pipe_through [:browser, :guardian]

    get "/register", RegistrationController, :new
    post "/register", RegistrationController, :create
    get "/login", SessionController, :new
    post "/login", SessionController, :create
  end

  scope "/", WebServerWeb do
    pipe_through [:browser, :guardian, :browser_auth]

    resources "/profile", ProfileController, only: [:show], singleton: true
    resources "/products", ProductController
    delete "/logout", SessionController, :delete
  end

  scope "/auth", WebServerWeb do
    pipe_through [:browser, :guardian]

    get "/:provider", AuthController, :request
    get "/:provider/callback", AuthController, :callback
  end

  # Other scopes may use custom stacks.
  # scope "/api", WebServerWeb do
  #   pipe_through :api
  # end

  # Enables LiveDashboard only for development
  #
  # If you want to use the LiveDashboard in production, you should put
  # it behind authentication and allow only admins to access it.
  # If your application does not have an admins-only section yet,
  # you can use Plug.BasicAuth to set up some basic authentication
  # as long as you are also using SSL (which you should anyway).
  if Mix.env() in [:dev, :test] do
    import Phoenix.LiveDashboard.Router

    scope "/" do
      pipe_through :browser
      live_dashboard "/dashboard", metrics: WebServerWeb.Telemetry
    end
  end
end

web_server/lib/web_server_web/views/layout_view.ex
defmodule WebServerWeb.LayoutView do
  use WebServerWeb, :view

  def get_account(conn) do
    WebServerWeb.Authentication.get_current_account(conn)
  end
end

web_server/lib/web_server_web/templates/layout/app.html.eex
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8"/>
    <meta http-equiv="X-UA-Compatible" content="IE=edge"/>
    <meta name="viewport" content="width=device-width, initial-scale=1.0"/>
    <title>WebServer · Phoenix Framework</title>
    <link rel="stylesheet" href="<%= Routes.static_path(@conn, "/css/app.css") %>"/>
    <script defer type="text/javascript" src="<%= Routes.static_path(@conn, "/js/app.js") %>"></script>
  </head>
  <body>
    <header>
      <section class="container">
        <% account = WebServerWeb.LayoutView.get_account(@conn) %>
        <%= if account do %>
          <nav class="navigation" role="navigation">
            <section class="container">
              <ul class="navigation-list">
                <li class="navigation-item">
                  <%= account.email %>
                </li>
                <li class="navigation-item">
                  <%= link("Profile", to: Routes.profile_path(@conn, :show)) %>
                </li>
                <li class="navigation-item">
                  <%= link("Products", to: Routes.product_path(@conn, :index)) %>
                </li>
                <li class="navigation-item">
                  <%= link("Log Out", to: Routes.session_path(@conn, :delete), method: :delete, class: "qa_sign_out") %>
                </li>
              </ul>
            </section>
          </nav>
        <% end %>
      </section>
    </header>
    <main role="main" class="container">
      <p class="alert alert-info" role="alert"><%= get_flash(@conn, :info) %></p>
      <p class="alert alert-danger" role="alert"><%= get_flash(@conn, :error) %></p>
      <%= @inner_content %>
    </main>
  </body>
</html>